"use client";
import { useState } from "react";
import { ArrowRight, ArrowLeft, Check, ChefHat } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

const steps = ["Your table", "Your routine", "Your details"];
const diets = ["No preferences", "Vegetarian", "Vegan", "Pescatarian", "Gluten-free", "Dairy-free", "High-protein"];
export default function Home() {
 const [step,setStep]=useState(0), [done,setDone]=useState(false), [busy,setBusy]=useState(false), [error,setError]=useState("");
 const [form,setForm]=useState({household:"2",diet:[] as string[],notes:"",day:"Either works",frequency:"Every week",meals:"4–5 meals",name:"",email:"",location:""});
 const update=(key:string,value:unknown)=>setForm(f=>({...f,[key]:value}));
 const chooseDiet=(d:string)=>update("diet",form.diet.includes(d)?form.diet.filter(x=>x!==d):d==="No preferences"?[d]:[...form.diet.filter(x=>x!=="No preferences"),d]);
 async function submit(e:React.FormEvent<HTMLFormElement>) { e.preventDefault(); if(step<2){setStep(step+1);return;} setBusy(true);setError("");try{const r=await fetch('https://formsubmit.co/ajax/antonyltran@gmail.com',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({...form,diet:form.diet.join(', ')||'Not specified',_subject:'New CREME interest',_template:'table'})});const result=await r.json();if(!r.ok||(result.success!==true&&result.success!=='true'))throw Error();setDone(true);}catch{setError("We couldn’t submit your interest. Your answers are still here — please try again.");}finally{setBusy(false);} }
 function choices(key:"household"|"day"|"frequency"|"meals",values:string[]){return <div className="choices">{values.map(v=><Button type="button" variant="outline" key={v} aria-pressed={form[key]===v} className={form[key]===v?"choice selected":"choice"} onClick={()=>update(key,v)}>{v}{form[key]===v&&<Check size={14}/>}</Button>)}</div>}
 return <main className="site"><header><a className="wordmark" href="./" aria-label="CREME home">CREME</a><span className="header-note">A little weekend prep. A whole lot of living.</span><span className="header-tag">PRIVATE CHEF, PERSONAL TOUCH</span></header>
 <div className="layout"><section className="story"><div className="eyebrow"><span/> THE WEEK AHEAD, TAKEN CARE OF</div><h1>Your kitchen. <br/>Your chef.<br/><em>Your weekend back.</em></h1><p className="intro">A private chef comes to your home on the weekend and preps meals around you. Good food, ready for real life.</p><div className="photo"><img src="./creme-food.png" alt="Fresh seasonal meals being prepared with colorful vegetables and herbs"/><div className="photo-caption"><ChefHat size={20}/><span>Made in your kitchen.<br/><strong>Made for your week.</strong></span></div></div><div className="story-footer"><span>PERSONAL MENUS</span><span>IN-HOME COOKING</span><span>WEEKEND PREP</span></div></section>
 <section className="form-side" aria-label="CREME interest form">{done?<div className="success" role="status"><div className="success-mark"><Check size={30}/></div><p className="eyebrow">YOU’RE ON THE LIST</p><h2>A better week<br/>is on the menu.</h2><p>Thanks, {form.name.split(' ')[0]}. Your interest has been submitted. CREME can reach you at <strong>{form.email}</strong> to discuss availability and next steps.</p><p className="fine">This is an expression of interest, not a confirmed booking.</p></div>:<><div className="form-intro"><div className="eyebrow">LET’S MAKE ROOM FOR GOOD FOOD</div><h2>A table set for <em>you.</em></h2><p>Tell us a little about your week. We’ll take it from there.</p></div><ol className="progress">{steps.map((s,i)=><li key={s} className={i<=step?'active':''} aria-current={i===step?'step':undefined}><span>{i<step?<Check size={13}/>:String(i+1).padStart(2,'0')}</span>{s}</li>)}</ol>
 <form onSubmit={submit}><div className="step-content" key={step}>
 {step===0&&<><div className="question"><h3>How many are we cooking for?</h3><p>Count everyone who’ll be pulling up a chair.</p>{choices('household',['1','2','3','4','5+'])}</div><div className="question"><h3>How do you like to eat?</h3><p>Select any preferences that feel like you. Optional.</p><div className="choices diets">{diets.map(d=><Button key={d} type="button" variant="outline" aria-pressed={form.diet.includes(d)} className={form.diet.includes(d)?'choice selected':'choice'} onClick={()=>chooseDiet(d)}>{d}{form.diet.includes(d)&&<Check size={14}/>}</Button>)}</div></div><div className="question"><label htmlFor="notes">Anything else on the menu? <span>Optional</span></label><Textarea id="notes" value={form.notes} onChange={e=>update('notes',e.target.value)} maxLength={2000} placeholder="Favorite foods, allergies, or anything we should know…"/><p className="fine">Any allergies will need to be confirmed with your chef.</p></div></>}
 {step===1&&<><div className="question"><h3>Which day suits your weekend?</h3><p>A little time in your kitchen, a head start on your week.</p>{choices('day',['Saturday','Sunday','Either works'])}</div><div className="question"><h3>How often would you like a chef?</h3>{choices('frequency',['Every week','Every other week','Occasionally'])}</div><div className="question"><h3>How many meals should we prep?</h3><p>For each person in your household, per visit.</p>{choices('meals',['2–3 meals','4–5 meals','6+ meals'])}</div></>}
 {step===2&&<><div className="question"><label htmlFor="name">Your name</label><Input id="name" autoComplete="name" placeholder="First and last name" required maxLength={120} value={form.name} onChange={e=>update('name',e.target.value)}/></div><div className="question"><label htmlFor="email">Email address</label><Input id="email" autoComplete="email" type="email" placeholder="you@example.com" required maxLength={254} value={form.email} onChange={e=>update('email',e.target.value)}/></div><div className="question"><label htmlFor="location">City & ZIP / postal code</label><Input id="location" autoComplete="postal-code" placeholder="Where would we be cooking?" required maxLength={180} value={form.location} onChange={e=>update('location',e.target.value)}/><p className="fine">This helps us understand where there’s interest.</p></div><p className="fine">By joining, you agree to be contacted by CREME about your interest. Your answers are sent to CREME through FormSubmit.</p></>}
 </div>{error&&<p role="alert" className="error">{error}</p>}<div className="form-actions">{step>0&&<Button type="button" variant="ghost" onClick={()=>setStep(step-1)} disabled={busy}><ArrowLeft/> Back</Button>}<Button className="next" type="submit" disabled={busy}>{busy?'Saving…':step===2?'Join the interest list':'Continue'}<ArrowRight size={18}/></Button></div><p className="form-footnote">{step===2?'No commitment. Just the start of something delicious.':'Takes about 2 minutes · No commitment'}</p></form></>}</section></div><footer><span className="mini-logo">CREME</span><span>Well fed. More present.</span><span>WEEKEND COOKING. WEEKDAY LIVING.</span></footer></main>
}
